### ISSUE TITLE
War file is not created

### ISSUE THREAD

**Issue by changja88** [ktorio/ktor-samples#14]
when I do ./gradlew :tomcat:run.
.war file is not created.

**Comment by soywiz** [comment]
Try `./gradlew tomcat-war:war` instead. It should put the war file inside `/deployment/tomcat-war/build/libs/tomcat-war.war`.

---

The `run` task triggers the `tomcatRun` task that doesn't generate the war file but runs directly without it.

```
./gradlew tomcat-war:tasks

...
war - Generates a war archive with all the compiled classes, the web-app content and the libraries.
...
tomcatJasper - Runs the JSP compiler and turns JSP pages into Java source.
tomcatRun - Uses your files as and where they are and deploys them to Tomcat.
tomcatRunWar - Assembles the webapp into a war and deploys it to Tomcat.
tomcatStop - Stops Tomcat.
...
```
