### ISSUE TITLE
Question about MPP sample

### ISSUE THREAD

**Issue by RR12** [ktorio/ktor-samples#25]
First of all thank you so much for the great project sample for MPP. I have 2 questions after trying out that sample.

1. Is it required to import these 2 lines below? What is the different between them?

```
import kotlin.coroutines.experimental.*
import kotlinx.coroutines.experimental.*
```

2. For now, do we only can use `dispatch_get_main_queue()` ? Since when I try to use `dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND.toLong(), 0)` my app just crash.

3. Is this AppCode issue that it can't recognize some coroutines classes?
<a href="https://ibb.co/jgWT39"><img src="https://preview.ibb.co/dHS1O9/Screen_Shot_1439_12_02_at_6_59_42_PM.png" alt="Screen_Shot_1439_12_02_at_6_59_42_PM" border="0"></a>

Here is the github url for my project : https://github.com/RR12/mpp-playground

**Comment by soywiz** [comment]
1st:
```
import kotlin.coroutines.experimental.*
import kotlinx.coroutines.experimental.*
```

The first import is the low-level coroutines part, that is part of Kotlin itself:
https://github.com/JetBrains/kotlin/tree/1.2.60/libraries/stdlib/src/kotlin/coroutines/experimental

The second import is from a higher level official library, but it is not included as part of the kotlin runtime:
https://github.com/Kotlin/kotlinx.coroutines

2nd, 3rd:
@e5l any tips here?

**Comment by e5l** [comment]
2. Unfortunately, there are no multithreaded coroutines yet and you have to run request and process response on the single queue. `HttpClient` use the main queue to execute requests. This limitation is temporal but it still exists.

3. It looks like the `AppCode` doesn't work properly with new kotlin-native plugin model(and it couldn't resolve the dependencies from Jars). You could file an issue. My personal advice is to left it as is, for now. You could write the common modules in `IDEA` where everything is fine.

**Comment by RR12** [comment]
Thank you so much for the explanations @soywiz @e5l ... Really appreciate it.

Yeah for now I just leave it as it is,  since it's run and working well so far. And yes, for now my workflow is to write my common and jvm/android module in IntelliJ/ Android Studio and write my K/N module in AppCode.
